UCSDTESC/Check-in

migrations/1-create_users.js, migrations/2-create_admins.js, migrations/3-create_events.js, migrations/4-seed_admins.js, migrations/5-seed_events.js, migrations/6-seed_users.js, package.json, src/assets/js/components/CheckboxButton.js, src/assets/js/data/Api.js, src/assets/js/pages/EventPage/index.js, src/assets/js/pages/UsersPage/index.js, src/assets/js/routes.js, src/assets/scss/components/_all.scss, src/assets/scss/components/_checkbox-button.scss, src/assets/scss/pages/_event.scss, src/server/models/admin.js, src/server/models/index.js, src/server/models/user.js, src/server/routes/api.js, src/server/routes/auth.js, src/server/routes/errors.js, src/server/routes/helper.js
Adds the Event Users page and seeds the database with a fake user associated with the existing event.
=> Added Users Table

src/assets/js/pages/HomePage/components/About.js, src/assets/scss/components/_about.scss
Event and previous event cards on the front-page
=> Added Event Cards

migrations/5-seed_events.js, src/server/config/mailer.js, src/server/routes/registration.js, src/views/emails/confirmation/html.pug, src/views/emails/style.css
Inlining CSS and added user name in Email To field
=> Fixed Email Styling

src/assets/js/auth/user/Forgot.js, src/server/config/mailer.js, src/server/routes/errors.js, src/server/routes/user.js, src/views/emails/forgot/html.pug, src/views/emails/forgot/subject.pug, src/views/emails/style.css
Sends a password reset email, and allows for resetting password through the page.
=> Added Password Reset Functionality

src/assets/js/components/User.js, src/assets/js/pages/DashboardPage/index.js, src/assets/js/pages/UsersPage/index.js, src/assets/js/proptypes/index.js, src/server/routes/api.js
View all registered users for admin,
=> Admin View All Users

migrations/5-seed_events.js, package-lock.json, src/assets/js/components/User.js, src/assets/js/pages/UsersPage/reducers/Columns.js
- Email cannot be edited by an admin anymore 
- Fixed a bug with the email field not showing up in the users table
=> Made Email Uneditable and Fixed Email's Accessor in User Table

src/assets/js/layouts/admin.js, src/assets/js/layouts/components/AdminSidebar.js, src/assets/js/pages/CheckinPage/index.js, src/assets/js/pages/DashboardPage/index.js, src/assets/scss/pages/_all.scss, src/assets/scss/pages/_checkin.scss, src/server/models/admin.js, src/server/models/event.js, src/server/routes/api.js, src/server/routes/helper.js
Removed unnecessary UI and simplified check-in workflow for volunteers
=> Check-In Fixes

src/assets/js/data/Api.js, src/assets/js/pages/ApplyPage/components/Header.js, src/assets/js/pages/ApplyPage/components/PersonalSection.js, src/assets/js/pages/ApplyPage/components/UserSection.js, src/assets/js/pages/ApplyPage/index.js, src/server/routes/errors.js, src/server/routes/registration.js
Checks to see if the user already has an account with TESC.events, and registers the user against that.
=> Re Register Application

migrations/13-add_options.js, src/assets/js/pages/ApplyPage/components/PersonalSection.js, src/assets/js/pages/ApplyPage/components/UserSection.js
- Minor Front End Alignment / Centering Changes
- Adds MLH Provisions Checkboxes to apply page
=> Added MLH Provisions Front End

migrations/13-add_options.js, src/assets/js/pages/ApplyPage/components/Fields.js, src/assets/js/pages/ApplyPage/components/PersonalSection.js, src/assets/js/pages/ApplyPage/components/UserSection.js, src/assets/js/pages/ApplyPage/validate.js, src/server/models/event.js, src/server/models/user.js, src/server/routes/registration.js, src/server/routes/user.js
- Adds an option to add diversity options for events
- Wording changes for MLH Provisions
=> Added Diversity Options To User Application

src/server/routes/api.js
Simple change so that the "Unique Universities" statistic for each event was independent of every other.
=> Fixed Distinct University Statistic

src/assets/js/components/User.js, src/assets/js/pages/UserPage/components/UserProfile.js, src/server/models/user.js, src/server/routes/errors.js, src/server/routes/registration.js
This PR makes university an unrequired field, adds a highSchool and updates user and admin UIs to show High School when University is not set.
Fixes #66
=> Fixed High School Registrations

src/assets/js/layouts/sponsor.js, src/assets/js/pages/ResumesPage/components/ResumeList.js, src/assets/js/pages/ResumesPage/index.js, src/assets/js/reducers/Admin/Filters.js, src/server/routes/api.js
- Adds a Graduate Option To Filter By
- Adds a status field to the sponsor table
=> Added Graduate Option And Status To Sponsor UI

src/assets/js/pages/ApplyPage/components/PersonalSection.js
=> Fixed Institution Card Spacing

src/assets/js/auth/user/actions/index.js, src/assets/js/data/helpers.js
=> Fixed Broken Login Message

package.json, src/server/routes/registration.js
=> Fixed Email Re-Send

migrations/13-add_options.js, src/assets/js/components/User.js, src/assets/js/pages/ApplyPage/components/PersonalSection.js, src/assets/js/pages/ApplyPage/components/ResponseSection.js, src/assets/js/pages/ApplyPage/index.js, src/assets/js/pages/ApplyPage/validate.js, src/assets/js/pages/EventPage/components/EventOptions.js, src/assets/js/pages/UserPage/components/UserProfile.js, src/assets/js/pages/UsersPage/components/ColumnEditor.js, src/assets/js/pages/UsersPage/reducers/Columns.js, src/assets/js/static/ColumnHeaders.js, src/assets/scss/components/_form.scss, src/server/models/event.js, src/server/models/user.js, src/server/routes/registration.js, src/server/routes/user.js
1) Added Extra Curriculars as an event option
2) Added Class Requirement (CSE 100 for now) as an event option
3) Fixed Bug where clicking on a blue column header button at the top of UsersPage broke the entire app
4) Added header names instead of direct variable names when adding columns to the table - will make another PR later to add a dropdown for this
#97 is merged into this
=> Added EC, Class Requirement and GPA, Major GPA Options

src/assets/js/components/EventCard.js, src/assets/js/pages/DashboardPage/components/EventList.js, src/assets/js/pages/HomePage/components/CurrentEvents.js, src/assets/scss/components/_event-card.scss
Moved event cards from the home page to their own component, for re-use on the dashboard page.
=> Created Consistent Admin Event Cards

src/client/data/AdminApi.ts, src/server/api/controllers/admin/ExportController.ts, src/server/api/controllers/index.ts
Regression from TypeScript rewrite - Export API wasn't being called
=> Fixed ExportController Not Being Called

src/client/components/User.tsx, src/client/utils/QRCodes.ts
Admins can now view a user's QR Code
=> Added QR code Functionality on Admin Side

src/client/pages/CheckinPage/index.tsx
=> Fixed Null Pointer For Manual Checkin

src/client/data/AdminApi.ts, src/client/layouts/sponsor.tsx, src/server/api/controllers/admin/ResumesController.ts
We'll rework this back to the old implementation once the scalability issues are resolved
=> Reworked Sponsor Tool Download To CSV Download

src/client/pages/UsersPage/components/UserList.tsx
Fixes #153 
Makes filtering case insensitive and renders booleans
=> Fix UsersPage Table To Have Case Insensitive Filtering And Render Boolean Fields

src/client/components/User.tsx
QoL change to add a dropdown to UsersPage for easier edits.
=> Moved Admin Side Status Box to Dropdown

src/client/components/Hero.tsx, src/client/layouts/public.tsx, src/client/pages/ApplyPage/components/UserSection.tsx, src/client/pages/ApplyPage/index.tsx, src/client/pages/EventPage/components/PreviewApplication.tsx, src/client/pages/EventPage/components/ViewApplication.tsx, src/client/pages/EventPage/index.tsx, src/client/routes.tsx
Also moved out rendering `<NavHeader>` to a public layout so we can render ApplyPage freely :)
=> Added Preview Application Feature When Application Is Closed

package-lock.json, src/client/pages/EventPage/components/AppsOverTimeStatistics.tsx, src/client/typings/victory.d.ts, tsconfig.json
Victory TypeScript typings have been out of date for years now, so instead of trying to merge into the official repository to fix it, I patched the prop interface manually.
=> Fixed Victory Typings

src/assets/scss/components/_form.scss
=> Fix Z Index Progress on Application Form

gulpfile.js
learnings from 2 hours i will never get back :)
=> Added Gulp Prod Build Disclaimer Doc
